Repository Sheweny/website, pull requests merged in 2021-08, with the labels that each got.

#5 Fixe guide and doc
  docs/README.md
  docs/doc/classes/ApplicationCommandsHandler.md
  docs/doc/classes/ButtonsHandler.md
  docs/doc/classes/EventsHandler.md
  docs/doc/classes/InhibitorsHandler.md
  docs/doc/classes/MessageCommandsHandler.md
  docs/doc/classes/SelectMenusHandler.md
  docs/doc/classes/ShewenyClient.md
  docs/doc/structures/ApplicationCommand.md
  docs/doc/structures/Button.md
  docs/doc/structures/Event.md
  docs/doc/structures/Inhibitor.md
  docs/doc/structures/MessageCommand.md
  docs/doc/structures/SelectMenu.md
  docs/doc/typedef/BaseHandlerOptions.md
  docs/doc/typedef/ClientHandlersOptions.md
  docs/doc/typedef/CommandOptions.md
  docs/doc/typedef/EventOptions.md
  docs/doc/typedef/HandlerApplicationCommandOptions.md
  docs/doc/typedef/InhibitorOptions.md
  docs/doc/typedef/MessageCommandHandlerOptions.md
  docs/doc/typedef/ShewenyClientOptions.md
  docs/guide/commands/Before.md
  docs/guide/handlers/buttons.md
  docs/guide/handlers/events.md
Labels: bug, documentation

#6 Change domain
  .github/workflows/deploy.yml
  bot/bot/config.json
  bot/bot/package-lock.json
  bot/bot/package.json
  bot/bot/src/index.js
  docs/.vuepress/config.js
Labels: documentation

#9 Some fixes
  docs/.vuepress/config.js
  docs/README.md
  docs/guide/buttons/Basic.md
  docs/guide/buttons/Before.md
  docs/guide/getting-started/Start.md
  docs/guide/inhibitors/Inhibitor.md
Labels: bug, documentation

#11 Fix/Update
  docs/.vuepress/components/Foo/Bar.vue
  docs/.vuepress/components/OtherComponent.vue
  docs/.vuepress/components/demo-component.vue
  docs/.vuepress/config.js
  docs/.vuepress/public/Sheweny.png
  docs/.vuepress/public/favicon.ico
  docs/.vuepress/public/hero.png
  docs/guide/cli/Installation.md
  docs/guide/cli/Usage.md
Labels: documentation, enhancement

#12 Add V2 link
  docs/README.md
  docs/guide/getting-started/Client.md
Labels: documentation
